- engi.go
- engi_glfw.go
As discussed in #9. Let me know if you have any remarks.
> Added support for FPS Limit. Currently the default is set to 120.

- font.go
It now copes with the closing of code.google.com
Fixes #8
It now builds when you download / update all packages. (Had to fix in order to get it running after fresh install)
> Updated font.go

- assets.go
- batch.go
- engi.go
- engi_glfw.go
- engi_js.go
- keys.go
It was ajhager/webgl, and is now paked/webgl.
Also added the PLUS and MINUS (numpad) keys.
> Updated webgl import path

- assets.go
- batch.go
- camera-systems.go
- camera.go
- camera_systems.go
- camera_test.go
- demos/edgescroller/escroller.go
- demos/keyboardscroller/kbscroller.go
- engi.go
- engi_glfw.go
- engi_js.go
- keys.go
- level.go
- math.go
- system.go
Objects are now positioned/drawn where they should be. The
`glfw` part worries about where the camera is, and where the
objects should be rendered.
Added some tests to ensure its behavior doesn't change over time.
Removed the `Clamp` function in the math file, because it's
probably better to use the `mgl32` package for things like that. No
need to define it twice.
Renamed the `gl` variable in engi, because having both `gl` and `Gl`,
referencing to the exact same object, doesn't make any sense.
I also added a `KeyboardScroller`. It's a `Systemer` people can add using 
```go
game.AddSystem(engi.NewKeyboardScroller(scrollSpeed, engi.W, engi.D, engi.S, engi.A))
```
And then everything works out-of-the-box. No need to create a separate `Entity` for it. 
Much like the `KeyboardScroller`, we now …
> Updated the Camera API

- assets.go
- batch.go
- camera.go
> Fixed Camera issues. 

- camera.go
- demos/edgescroller/escroller.go
- demos/hud/hud.go
- demos/zoom/zoom.go
- world.go
Thereby updated all examples, and verified they work.
Also added a new example: zoom.go
Please review the code, especially at the bottom. @paked 
Fixes #26.
> Updated default Camera values

- animation.go
- camera_systems.go
- components.go
- demos/falling/falling.go
- demos/hello/hello.go
- demos/pong/pong.go
- system.go
- world.go
- world_test.go
Also removed the variables and some pointers, to enable the compiler
to (possibly) speed things up even faster.
Fixes #32.
> Renamed Name() to Type()

- demos/pause/pause.go
- pause.go
Change-Id: I8a1b28c52dd8c70932b4ef056e54afea20b15e9a
> fix for a small regression issue with pause system

- components.go
- demos/animation/anim.go
- demos/edgescroller/escroller.go
- demos/entity/entity.go
- demos/falling/falling.go
- demos/hello/hello.go
- demos/hud/hud.go
- demos/keyboardscroller/kbscroller.go
- demos/pause/pause.go
- demos/pong/pong.go
- demos/tilemap.go
- demos/zoom/zoom.go
Change-Id: I740f705e1256e4b2c9a1225ff9e4d45687638208
> pointers for components

- demos/animation/anim.go
- demos/audio/audio.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/pause/pause.go
- demos/pong/pong.go
- demos/tilemap.go
- world.go
Exist = false may not be performant way to remove enitites.
Imagine a game when there are bullets, lots of small short lived objects. If they are all stored in the world the game would run very slowly after a while not to mention memory footprint.
> Added ability to remove entities from the world

- entity.go
- system.go
Performance increased about `10-15%`.
Performance increased about `20-25%`. 
(I know the branch has an incorrect name ;-) )
> Tuned Performance

- assets.go
- demos/pong/pong.go
- engi_glfw.go
- font.go
Updated demo to use new feature.
Nothing special, but very nice to use.
> Fonts can now be preloaded

- animation.go
- assets.go
- audio.go
- benchmarks_test.go
- camera.go
- camera_systems.go
- demos/animation/anim.go
- demos/audio/audio.go
- demos/edgescroller/escroller.go
- demos/entity/entity.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello/hello.go
- demos/hud/hud.go
- demos/keyboardscroller/kbscroller.go
- demos/pause/pause.go
- demos/pong/pong.go
- demos/zoom/zoom.go
- engi.go
- engi_glfw.go
- input.go
- level.go
- pause.go
- responder.go
- system.go
- system_test.go
- world.go
- world_test.go
This means all mouse movement is now saved in the Mouse variable.
(not yet tested for "drag" movement)
Updated all examples to reflect changes.
Please review @paked @matiwinnetou because it has quite some changes. 
This is ~~almost~~ done; ~~only need to fix the `Scroll` behavior.~~
> Refactored Responder to CustomGame

- assets.go
Fixes #66. Also improved performance because I simplified the formula.
> Fixed HUDGround ratio

- engi_glfw.go
One should also update the webgl package.
> Added support for RGBA.

- batch.go
> Hotfix draw performance

- README.md
- audio_player.go
- math_test.go
- responder.go
- system_test.go
- world.go
- world_test.go
Added concurrent execution for updates to system entities.  Initial performance tuning done to maximize the effect of concurrency, initially coded to maintain serial execution below 20 entities per system.  
Tuning should be continued upon each entity update.
> Concurrent system updates added

- animation.go
- audio.go
- camera.go
- collision.go
- demos/animation/anim.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello/hello.go
- demos/hide/hide.go
- demos/pong/pong.go
- pause.go
- render.go
- system.go
- world.go
**THIS IS A BREAKING CHANGE (!).**
Also updated all demos and ensured they worked with this change.
Fixes #93.
> Changed System.New() to System.New(*World)

- demos/pause/pause.go
- engi_glfw.go
Fixes zooming bug and fixes the `Pause` demo.
> Hotfix zoom

- assets.go
- batch.go
- font.go
- level.go
- render.go
> Refactored uint32 and engi.Color to color.Color

- engi_glfw.go
> Fix default WorldBounds

- audio_windows.go
- batch.go
- demos/keyboardscroller/kbscroller.go
- demos/mouse/README.md
- demos/mouse/mouse.go
- engi.go
- engi_glfw.go
- mouse.go
Also added a demo for the mouse events. See #59.
The function `engi.SetScaleOnResize` allows user to say:
"I want things to become bigger on resize" (i.e. Pong), or
"I want to be able to see more things on resize" (i.e. KeyboardScroller).
See #65.
The `MouseSystem` and `CameraSystem` are changed accordingly.
Also created a separate `audio.go` file for Windows, to
be sure it also builds on Windows. Fixes #121.
> Added MouseEvents AND changed window resize

- assets.go
- batch.go
- demos/pong/pong.go
- engi_glfw.go
Updated HUD rendering, which fixed #123.
Also added a line to the pong demo to ensure it scales on resizing the window.
Feel free to review and merge @paked @matiwinnetou
> Hotfix pong and Fixed hud

- audio_player.go
> Revert "fix golang/x/mobile/exp/audio call failed"

- audio.go
Should fix #140.
Could you check if this fixes the problem, @varomix?
> Fixed audio on Windows

- demos/README.md
I wrote this up really quickly on the bus... It'll need some editing.
@EtienneBruines @matiwinnetou Want to take a peek at it?
> Add index to demos README

- demos/animation/anim.go
- demos/audio/audio.go
- demos/edgescroller/escroller.go
- demos/entity/entity.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello/hello.go
- demos/hide/hide.go
- demos/hud/hud.go
- demos/keyboardscroller/kbscroller.go
- demos/mouse/mouse.go
- demos/pong/pong.go
- demos/scenes/scenes.go
- demos/zoom/zoom.go
- engi.go
Fix #142 
Please review @EtienneBruines @faide :heart:
> Move SetBg to use standard library color package

- demos/pong/pong.go
Fixes https://github.com/paked/engi/issues/159
> Check to ensure paddles don't go out of the screen

- demos/animation/anim.go
- demos/audio/audio.go
- demos/edgescroller/escroller.go
- demos/entity/entity.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello/hello.go
- demos/hide/hide.go
- demos/hud/hud.go
- demos/keyboardscroller/kbscroller.go
- demos/mouse/mouse.go
- demos/pong/pong.go
- demos/scenes/scenes.go
- demos/tilemap.go
- demos/zoom/zoom.go
- engi.go
> Renamed engi.Open to engi.Run

- demos/animation/anim.go
- demos/audio/audio.go
- demos/edgescroller/escroller.go
- demos/entity/entity.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello/hello.go
- demos/hide/hide.go
- demos/hud/hud.go
- demos/keyboardscroller/kbscroller.go
- demos/mouse/mouse.go
- demos/pong/pong.go
- demos/scenes/scenes.go
- demos/tilemap.go
- demos/zoom/zoom.go
- engo.go
BREAKING CHANGE (!). Refactored `SetBg` to `SetBackground`
Fixes #176.
> Renamed SetBg to SetBackground

- camera.go
- demos/edgescroller/escroller.go
- demos/hud/hud.go
- demos/keyboardscroller/kbscroller.go
- demos/mouse/mouse.go
- demos/zoom/zoom.go
- engo.go
- engo_glfw.go
- mouse.go
- render.go
- shaders.go
Should fix #151. Changed default FPS from 120 to 60. 
Changed resolution of `ZoomDemo` from 400x400 to 900x900. 
Please review.
> Changed PriorityLevel to ZIndex

- README.md
I understand this is a rather sensitive topic, and I'm running on low amounts of sleep... So I'm not quite sure I remembered everything correctly. If anyone wants to discuss things privately, please do not hesitate to give me a [private message on Gitter](https://gitter.im/paked).
@EtienneBruines I'm trying to put all the work you have done into one line, any help with that?
> Add history and credits section to README

- README.md
- demos/animation/anim.go
- demos/audio/audio.go
- demos/edgescroller/escroller.go
- demos/entity/entity.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello/hello.go
- demos/hide/hide.go
- demos/hud/hud.go
- demos/keyboardscroller/kbscroller.go
- demos/mouse/mouse.go
- demos/pong/pong.go
- demos/scenes/scenes.go
- demos/tilemap.go
- demos/zoom/zoom.go
FIxes https://github.com/EngoEngine/engo/issues/184
> Updated import paths in README and demos

- benchmarks_test.go
- demos/animation/anim.go
- demos/audio/audio.go
- demos/edgescroller/escroller.go
- demos/entity/README.md
- demos/entity/entity.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello/README.md
- demos/hello/hello.go
- demos/hide/hide.go
- demos/hud/hud.go
- demos/keyboardscroller/kbscroller.go
- demos/mouse/mouse.go
- demos/pong/pong.go
- demos/scenes/scenes.go
- demos/tilemap.go
- demos/zoom/zoom.go
I hope I didn't make any mistakes.
> Changed NewEntity to new syntax

- camera.go
- demos/hide/hide.go
- demos/incrementalcamera/README.md
- demos/incrementalcamera/incrcamera.go
- render.go
Important fix for the RenderComponent, now "visible" is the default,
instead of "hidden".
------------
This PR has quite some priority due to the "fix" it includes for the `RenderComponent`. Current `master` branch will not show the desired behavior. 
Ready for review.
> Added gradual camera movements + RenderComponent.Visible fix

- README.md
Ensuring that the badge shows the build status of the `master` branch. 
Merge upon approval @paked @otraore
> Badge to `master`

- assets.go
- assets_test.go
> Handle Resources without extensions properly

- engo_glfw.go
- message.go
- shaders.go
It's being dispatched wheneever we change our game window size. Everyone can
listen for those message and use it as they want to. The DefaultShader is an
excellent example of that.
Fixes #65. 
Ready for review.
> Added WindowResizeMessage

- assets.go
We can now call Preload as often as we'd like, because
resources that have been loaded already, will be re-used.
Fixes #127 
Ready for review and merge.
> Added resource caching

- README.md
> Created a list of breaking changes

- demos/animation/anim.go
- demos/audio/audio.go
- demos/edgescroller/escroller.go
- demos/exit/exit.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello-world/hello.go
- demos/hide/hide.go
- demos/hud/hud.go
- demos/incrementalcamera/incrcamera.go
- demos/keyboardscroller/kbscroller.go
- demos/mouse/mouse.go
- demos/pong/pong.go
- demos/scale/scale.go
- demos/scenes/scenes.go
- demos/zoom/zoom.go
- engo.go
- engo_glfw.go
- scene.go
> Made Exit, Hide and Show optional

- demos/animation/anim.go
- demos/demoutils/utils.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello-world/hello.go
- demos/hide/hide.go
- demos/mouse/mouse.go
- demos/pong/pong.go
- demos/scale/scale.go
- demos/scenes/scenes.go
- render.go
Thank you @mewmew for pointing this out.
> Fix RenderComponent constructor

- animation.go
- demos/animation/anim.go
> Add default and looping animations

- demos/pong/pong.go
Fixes #241. 
Merge whenever you feel like it.
> Renamed BallSystem to BounceSystem within Pong

- shaders.go
this fixes reusing a texture like a tilemap atlas and changing offsets
> check for lastBuffer for redraw

- audio.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/pong/pong.go
- engo_glfw.go
- engo_js.go
- render.go
Fixes https://github.com/EngoEngine/engo/issues/212#
> Renamed Width() and Height() to fix #212

- axis.go
- button.go
- camera.go
- demos/animation/anim.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello-world/hello.go
- demos/hud/hud.go
- demos/input/input.go
- demos/keyboardscroller/kbscroller.go
- demos/mouse/mouse.go
- demos/pong/pong.go
- engo.go
- engo_glfw.go
- engo_js.go
- input.go
- input_data.go
- keys.go
This is the result of #252.
I'd really appreciate some code review while I am finishing everything off.
**TODO**
> Rewrite input management

- README.md
- appveyor.yml
Adding in windows to our ci suite using appveyor
> Add Windows to CI

- engo_glfw.go
Fixes https://github.com/EngoEngine/engo/issues/300
> Hotfix for glfw's canvasHeight

- demos/hud/README.md
Fix for README file that wasn't updated to reflect the new package changes
> Fix package name in README.md for hud demo

- README.md
- common/collision.go
- common/collision_test.go
- common/mouse.go
- math.go
`SpaceComponent.AABB` is now no longer used (but still exists
for those that want to use it).
We now use and offer a `Within` method, checking whether or not
a given point is within the bounds of the `SpaceComponent`,
taking into account things as `Rotation` and floating precision.
It is feature-complete / done, so please review and merge. :smile:
> Fixed #310

- common/audio.go
- common/camera.go
- common/camera_test.go
- common/mouse.go
- common/render.go
- common/render_shaders.go
- common/render_shaders_test.go
> cameraSystem is now CameraSystem (exported)

- README.md
As per @hydroflame's request, we're not mentioning `lux` in our `README`, nor him personally.
> Fixes #328

- README.md
- assets.go
- demos/entityscroller/entityscroller.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/pong/pong.go
- demos/scale/scale.go
> Merge Load and LoadMany into one extendable method

- .runtests.sh
- axis.go
- cursor.go
- engo.go
- engo_glfw.go
- engo_js.go
- engo_mobile.go
- input_data.go
- keys.go
- message.go
Adds documentation to the engo.io/engo package (Really close to full coverage). As stated in the title this only covers engo.io/engo. Packages like engo.io/engo/common are going to be done in upcoming pull requests.
> Add documentation to engo.io/engo package 

- common/camera.go
- common/collision.go
- common/mouse.go
- common/render_shaders.go
- demos/rotation/rotation.go
- math.go
> Update luxengine/math to engoengine/math

- common/animation.go
- math.go
As [discussed by @mewmew](https://github.com/EngoEngine/engo/issues/313#issuecomment-221848332) 
Fixes: #313
> Add Within helper method to engo.Point

- demos/README.md
Fixes: https://github.com/EngoEngine/engo/issues/75
> Add all the demos to demos/README.md

- common/camera.go
- engo_glfw.go
- engo_js.go
- engo_mobile.go
Deprecates / replaces https://github.com/EngoEngine/engo/pull/352. 
This is the "correct" fix for the retina displays.
> Hotfix retina display

- .runtests.sh
- .travis.yml
Fixes: https://github.com/EngoEngine/engo/issues/294
> Check for unnecessary conversions during tests

- demos/adventure/README.md
Fix format and syntax highlighting on adventure demo
> Fix adventure demo README

- README.md
- common/render_filetype.go
- common/tmx_level.go
- demos/entityscroller/entityscroller.go
- demos/falling/falling.go
- demos/headless/headless.go
- demos/hello-world/hello.go
- demos/hide/hide.go
- demos/mouse-follow/follow.go
- demos/mouse/mouse.go
- demos/pong/pong.go
- demos/rotation/rotation.go
- demos/scale/scale.go
- demos/scenes/scenes.go
> Rename PreloadedSpriteSingle to LoadedSprite

- demos/adventure/adventure.go
Idea taken from the pong demo - precurser to adding collisions for the trees, I wanted the speed and movement separated from  the controls.
> refactor adventure demo to use a SpeedSystem

- common/animation.go
Please see commit messages for change details.
> common: animation improvements

- README.md
> Update readme on optional scene methods (#383)

- CONTRIBUTING.md
> Add a contributing guidelines

- README.md
> Add git requirement to README

- .runtests.sh
- .travis.yml
This is occurring because gopherjs requires go 1.8 and gomobile isn't building on 1.8.
> Fix travis build

- axis.go
- common/mouse.go
- common/render_shaders.go
- engo_glfw.go
- engo_js.go
- engo_mobile.go
Fixed the mouse cursor offsets in Android (#449) and JS (#428) without having to edit the shader stuff and worry about camera / window / canvas interactions being all messed up by it.
The code used for testing can be found here
https://github.com/Noofbiz/MouseTests
but is just a mashup of several demos I thought would be the most affected. Ran the demos on their own as well, looks good from my end.
> Mouse cursor offsets

- README.md
Correction in word "organization" at the end of the paragraph.
> Typo correction at History

- common/render.go
This function will be used to check if an entity exists (and where) into the entities slice, this will prevents entity's duplicity in the system that can causes a double render process for some entities if these was added twice.
This function could also be called from the Remove function to get the position of the entity that will be remove from the system.
> Adding EntityExists function to RenderSystem

- common/font.go
created a dynamic buffer, because as the font size increases the buffer winds up not being big enough between glyphs and sometimes they bleed in
> Font height buffer

- common/collision.go
Now the center gotten and set from center in the space component adjusts for rotation properly
> center changes

- common/collision.go
Was adding instead of setting equal.
> center fix

- demos/pong/pong.go
score was added to render and score system twice in the pong demo. This removes the second one.
> score added twice

- common/tmx_level.go
- allow line ending commas
- allow TilEd style CSV where there are line ending commas except in the last line
- propagate errors
Signed-off-by: gabre <gabre@caesar.elte.hu>
> Allow line ending commas in TMX CSV

- common/level.go
- common/tmx_level.go
Signed-off-by: gabre <gabre@caesar.elte.hu>
> Allow TMX parser to use tile size defined in tilesheet

- engo_js.go
added a key polling function, and the callbacks just record the keypresses into a poll rather than set the keys themselves. This fixes #491
> key polling

- engo.go
- engo_glfw.go
This way things that refer to the window size, such as Mouse systems, Movement systems, Scale systems, etc. can utilize Headless mode in their test cases. This closes #500
> setup fake window in headless mode

- common/font.go
Now returns the width and height of the Text drawable from a FontAtlas. This closes #488 and #381
> Text Width and Height

- assets.go
- clock.go
- common/audio_player.go
- common/mouse.go
- engo.go
- engo_glfw.go
- engo_js.go
- engo_mobile.go
- engo_mobile_bind.go
- input.go
- keys.go
- math.go
> Linted engo

- engo_glfw.go
Accidentally removed the whole init.
> Re-lock OS thread

- common/font.go
- common/render_shaders.go
> Added text background to cover line and letter spacing

- common/font.go
revert using the font metrics to get line height. It doesn't work for all fonts.
> fixed font height when using Render()

- common/render_shaders.go
Rather than doing it through the fragment shader. Closes #467 and #427
> Re-implemented the circle drawing using a rotation method

- engo_mobile.go
- engo_mobile_bind.go
> fps tickers added to mobile

- assets_test.go
> add tests for assets and file loader

- common/camera.go
- demos/adventure/adventure.go
> normalize diagonal camera movement

- demos/adventure/adventure.go
> adventure control now checks if buttons are down when others are released

- math.go
- math_test.go
> #560 added Line.AngleDeg method

- math.go
- math_test.go
> engo.Point methods now return the point

- common/audio.go
- engo_mobile_bind.go
- engo_mobile_bind_ios.go
mobile gets choppy with the buffer used for desktop / js
> bigger buffer for mobile

- .before_install.sh
- common/camera.go
- common/render.go
- common/render_shaders.go
> update shader camera when the scene changes / new camera is added.

- .travis.yml
- common/render_shaders.go
changed the borders by doing rectangles instead of lines, so we can control the border size beyond gl's line width (it is min and max of 1 on webgl!).
> draw lines by drawing rectangles for shapes

- engo.go
- message.go
> Data Races detected on the MessageManager

- engo_glfw.go
this will fix it until go's glfw can be updated
> Glfw mojave fix

- common/audio.go
Fixes #589.
Put oto and the read buffers on it's own goroutine. This allows audio to read / write without slowing the other systems down.
> separate oto on its own goroutine

- common/render.go
- common/render_shaders.go
In the case of writing an own shader, there is now the possibility to access the buffer / buffer content from the render component
> Export the buffer and buffer content

- README.md
- common/render_shaders.go
and changed newCamera to work for all shaders added
> added SetCamera method to Shader interface, implemented it

- common/internal/decode/convert/convert.go
- math.go
- message.go
- message_test.go
Unfortunately, there are still two linting issues that cannot be fixed without breaking backwards compatibility. :(
> Fix several linting issues that are backwards compatible.

- engo.go
- engo_empty.go
- engo_glfw.go
- engo_js.go
- engo_sdl.go
Instead of a RWMutex and a bool, use a channel for signaling when the
game should exit. This is less error prone, more conventional, and
an ultimately clearner implementation.
> Use a channel for closeGame.

- demos/README.md
Removed the dead Entity link from the demo README and added a section for the Entity Scroller demo.
> Update demo readme

- common/camera.go
> skip EntityScroller update loop if target entity is nil

- common/render_shaders.go
Got lost somewhere during the sprite batching fix. Re-added them. ^_^
> fixes for camera zoom and global scale

- common/font.go
This will be useful if you need to generate Font Atlas. Exposing it is no harm
> expose generateFontAtlas in Font

- common/audio_filetype.go
- common/render_filetype.go
> add svg support

- common/render.go
> added default render scale to be 1

- common/render.go
- demos/tilemap/tilemap.go
> Tmx render order fix

- common/mouse.go
> fix mouse coordinates for scale on resize

- common/render_shaders.go
> only multiple view and projection when needed

- engo_glfw.go
That change fixes the issue #681.
> fix width/height at fullscreen

- demos/falling/falling.go
This PR fixes a memory leak. Each stone adds itself as references to the RenderSystem, FallingSystem and CollisionSystem. All references of them were never removed.
The remove-functions were implemented (not completely...) but never called.
So I extended it to remove all corresponding references and call it when the stones reach the bottom.
> fix memory leak in Demo "falling"

- engo_glfw.go
- go.mod
- go.sum
- input_keys_glfw.go
> update to glfw 3.3.2

- common/fps.go
> Update FPS System

- script/verify-tutorial.sh
So we don't have to call go mod on running
> Added go modules to traffic manager tutorial

- common/animation.go
> Add current frame to AnimationComponent

- common/render_shaders_shapes.go
> Fixed position of circle border

- common/render_shaders_shapes.go
This plus the last two close #761 
Switched out triangle fan for triangle strip when drawing the borders of circles/arcs. This makes it so we can get outlines of circles/arcs by having a border and a transparent shape ^_^!
> added support for transparent circles/arcs with borders

- axis.go
- demos/gamepad/README.md
- demos/gamepad/gamepad.go
- engo_glfw.go
- engo_js.go
- gamepads.go
- gamepads_empty.go
- gamepads_glfw.go
- gamepads_js.go
- input.go
Added gamepad support for GLFW and the web. Also added a demo to show how to use it.
> Gamepad support

- demos/audio/README.md
- demos/audio/audio.go
fixes #783, they work fine with the demo. My issue must be elsewhere. Added the functionality to the demo.
> added pause feature to demo

- engo_glfw.go
- engo_mobile.go
- engo_mobile_bind_ios.go
- gamepads_glfw.go
- go.mod
- go.sum
- input_keys.go
- input_keys_glfw.go
> Add support for Apple M1

- common/render_filetype.go
> added support for loading gifs as a spritesheet
