README.md
Hey everyone,
In an attempt to open up engi development and allow its __users__ to contribute ideas and requests we have opened up a slack and a trello board. This pull request adds that information to the README. If you are making a game or prototype in engi please stop by and shout us your feedback. I am very flexible as to what kind of path the roadmap takes. So, if you have any suggestions I would love to hear them.
ps. I will leave this open for a few hours, as it is a good way of making an "announcement".
=> [ANNOUNCEMENT] Update README with information on slack and trello

assets.go, batch.go, demos/hud/hud.go, level.go, responder.go, system.go, world.go
See the example on how to use it, and see if you agree on the "API" that's needed. 
Summary: everything above `HUDGround` is rendered as a HUD, up to `HighestGround`. 
Fixes #22.
=> HUD example and API

system.go
Whenever an item requiring the RenderSystem, didn't have a SpaceComponent, engi would crash.
This is fixed now.
=> Fixed bug in RenderSystem

demos/audio/audio.go
The previous audio example contained animation and movement.
IMO all examples should be their own little feature, and not combine the two together (Unless they are a sample game, like pong).
=> Fix audio example being too complex

world.go
`append` already increases length and capacity, so if you create something with length `100`, and then `append` 100 things to it, then it ends up with a length of `200`.
=> Fixed empty entries in World.Entities

animation.go, assets.go, audio.go, camera.go, collision.go, entity.go, entity_test.go, pause.go, render.go, world.go, world_test.go
It shows that using `ComponentFast` a lot faster.
```
BenchmarkComponent-8          	   20000	    155262 ns/op	   16200 B/op	    1002 allocs/op
BenchmarkComponentDouble-8    	   10000	    266979 ns/op	   24200 B/op	    2002 allocs/op
BenchmarkComponentFast-8      	   50000	     70341 ns/op	    8200 B/op	       2 allocs/op
BenchmarkComponentFastDouble-8	   30000	     86215 ns/op	    8200 B/op	       2 allocs/op
```
* The benchmark is: how long does it take for one iteration / frame to run, with 1000 `Entity`s tied to one `System`, which either uses `GetComponent`, or `ComponentFast` to get its `Component`s. 
* note that this means that the `ns/op` also includes other stuff, unrelated to `GetComponent`, such as iterating over all `Entity`s. 
* The `Double` postfix means that it tries to …
=> Added ComponentFast + Benchmarks

collision.go, system.go, world.go
`Systemer` now includes a function `RunInParallel`, which indicates whether or not the `Entity`s should be processed in Parallel. 
`CollisionSystem` only benefits from `RunInParallel`, if it has more than 40 entities. This is because `CollisionSystem` is quite fast when there's less than 40 entities, and the overhead of starting goroutines is more. 
Each `System` has its own turning point, which can be defined without much effort (see code).
=> Added RunInParallel

system.go, world.go
When adding a `System` to `World`, it's appended
to the end, and then a quicksort algorithm is used
to sort it according to `System.Priority()`.
Fixes #105.
=> Sorting Systems in World

ecs/world.go, engi.go, engi_glfw.go, render.go, scene.go
Fixes #126 and fixes #128.
Global variables are now updated on Scene creation (whenever
we initialize a new World instance). These values are saved
in a sceneWrapper, so we don't always have to reinitialize.
CameraSystem is now set on Scene creation, since this was
hard to do within RenderSystem (as it is Scene-specific).
Ready for review @paked.
=> Fixed some global variables wrt Scene

audio_player.go
On go 1.5.1, update golang.org/mobile/ to the latest version.
Fix build error, though it still has no sound.
=> fix golang/x/mobile/exp/audio call failed

font.go, shaders.go
`HUDShader` now works mostly like `DefaultShader`,
instead of the (experimental) optimalizations.
More specifically: instead of having an `ELEMENT_ARRAY_BUFFER`
with the coordinates (of where to draw), and calling a single `DrawElements`; it now
works by calling `DrawElements` every time and setting the location as uniform (across the vertices),
instead of in the buffer.
Fixes #144.
Review if you want, LGTM.
=> Removed experimental HUDShader design

font.go
`font.TTF` is now public. Even though it's mostly used internally,
it's nice to be able to read/change the value from the outside.
I also refactored `RenderNRGBA` from the `Render` function - this is because someone might not want a `Texture`, but only an intermediary `NRGBA` (possibly doing some stuff to it, before creating a `Texture` from it).
=> Font.TTF is now public

benchmarks_test.go, camera.go, camera_test.go, demos/animation/anim.go, demos/audio/audio.go, demos/edgescroller/escroller.go, demos/entity/entity.go, demos/falling/falling.go, demos/headless/headless.go, demos/hello/hello.go, demos/hide/hide.go, demos/hud/hud.go, demos/keyboardscroller/kbscroller.go, demos/mouse/mouse.go, demos/pong/pong.go, demos/scenes/scenes.go, demos/tilemap.go, demos/zoom/zoom.go, ecs/entity.go, ecs/world.go, mouse.go, utils_test.go
Hi,
Here is the beginning of a PR / Proposition to add some control / error checking on the entity requirements. ATM the PR only adds logging to warn the developer an entity is being added to a world that does not have the sufficient systems to support its operation.
We could add an error return to the  (*ecs.World).AddEntity signature and this would break all previous code relying on the old signature. Should we make this breaking change while we can or should we just keep the logging version?
Introducing this new feature I added a new private field (systemMap) to ecs.World for my own use and I also took advantage of it in (*ecs.World).HasSystem() implementation.
=> Detect unmet dependencies in entities at adding time to world

mouse.go
Instead of resetting most values to false, we're now
forgetting every value from the last frame (with some
exceptions), to ensure things like `Click` don't fire twice. (which they do now)
Would you like to review @faide ?
=> Fixed issue where MouseComponent would stay Clicked

render.go
Values like `Drawable`, `Scale` and `PriorityLevel` require changes
to be done through a separate `SetXXXXXX` function (for caching purposes).
With this commit, the values that were once set by such a function,
can now be read.
Small PR, so feel free to merge.
=> RenderComponent now has readable values

animation.go, audio.go, audio_windows.go, benchmarks_test.go, camera.go, camera_test.go, collision.go, demos/animation/anim.go, demos/edgescroller/escroller.go, demos/falling/falling.go, demos/headless/headless.go, demos/hello/hello.go, demos/hide/hide.go, demos/hud/hud.go, demos/mouse/mouse.go, demos/pong/pong.go, demos/scenes/scenes.go, demos/zoom/zoom.go, ecs/entity.go, ecs/entity_test.go, ecs/linear.go, ecs/system.go, ecs/world.go, ecs/world_test.go, mouse.go, render.go
Fixes #119
Things like
```go
type MyCustomSystem struct {
*ecs.System
}
```
have become
```go
type MyCustomSystem struct {
*ecs.BasicSystemWrapper
}
```
----------------
Things like
```go
func (m *MyCustomSystem) New(*ecs.World) {
m.System = ecs.NewSystem()
}
```
have become
```go
func (m *MyCustomSystem) New(*ecs.World) {
m.BasicSystemWrapper = ecs.NewBasicSystemWrapper(m)
}
```
------------
Things like
```go
func (*MyCustomSystem) Update(*ecs.Entity, float32) {}
```
have become
```go
func (*MyCustomSystem) EUpdate(*ecs.Entity, float32) {}
```
A valid `System` (which you can add to a `World` instance), is this:
```go
type MyCustomSystem struct {}
func (*MyCustomSystem) Type() string { return "MyCustomSystem" }
func (*MyCustomSystem) Priority() int { return 1 }
func (*MyCustomSystem) …
```
=> Changed Systemer to System interface

audio.go, audio_player.go, audio_windows.go
Still does not fix the usage of audio on Windows, just
handles the compilation.
Fixes #140.
=> Fixed compiler issues on Windows

engo.go
One can now only import from `engo.io/engo`.
=> Added canonical import path obligation

.travis.yml
Not sure if `go1.6.1` or `go1.6` is valid. We'll just have to wait and see.
=> Only master, and only latest go

clock.go, common/font.go
```
u@x1 ~/g/s/e/engo> unconvert engo.io/ecs engo.io/engo engo.io/engo/common
/home/u/goget/src/engo.io/engo/clock.go:53:16: unnecessary conversion
/home/u/goget/src/engo.io/engo/common/font.go:131:22: unnecessary conversion
```
https://github.com/mdempsky/unconvert
=> Remove unnecessary conversions found by unconvert

clock.go
- Short:
* Faster tick method
* Decrease structure size
* Remove import of math package
- No more modulus on a float value, messy idea any way.
- No excessive divisions or multiplications inside Tick() or Time(), the Time internals are not optimal for this use case. (See links**)
- Size of the struct is now 40 bytes vs 72 bytes on the original, Time stores a extra pointer and caused padding inside the Clock struct. (Leaves room for 3 event pointers inside the 64 byte bounds of a cash line)
**Time.Sub()
https://golang.org/src/time/time.go?s=18822:18856#L618
**Time.UnixNano()
https://golang.org/src/time/time.go?s=24254:24284#L825
**Duration.Seconds()
https://golang.org/src/time/time.go?s=17832:17867#L579
***Note: In case Delta() is only called once or twice every frame this is fine, but …
=> Slimmer engo clock internals

clock.go, engo_glfw.go, engo_js.go, engo_mobile.go
By doing the start tick before the main loop the frame stamp inside the clock gets reset and this will minimize the delta time on the first frame.
Moving the Tick inside loop to run first reduces the delta time on the first frame even more and ensures a normal delta time in the second frame. (Having the tick first is also a plus if fixed physics are added at some point)
Note: Reordered the main loop to be the same on all targets, there is no reason to have them update in a different order ? The web build still seems to build and run fine, I'm not able to test the mobile build.
---
Other options considered:
- Move the clock creation to the start of the loop ? The clock is public and can be accessed in the loading before the main loop starts. Having 'nil' dangling out of the public …
=> Fix: Delta Time in the first two frames

common/collision.go, common/collision_test.go, common/mouse.go
My first PR (ever, probably) so, please, check everything is fine. I ran `go test engo.io/engo` and `go test engo.io/engo/common` and they pass; hoping that's enough.
This should fix the issue in #313 regarding the SpaceComponent.Within renaming to Contains.
=> Renamed SpaceComponent.Within to Contains, #313

common/collision.go, math.go
Unfortunately `luxengine/glm` has been breaking recently, and in order to make the lives of our users easier we've set up a mirror which *we* can move in changes when we like. This continues to allow the original author to experiment and optimise, while we can use it without fear of breaking all the things.
=> Vendor glm

common/mouse.go
Currently, even though you hide something, it can receive hover/click events. 
This is unwanted, because you can click something that's explicitely hidden. If you want something invisible, but clickable, you should set alpha to 0, instead of defining `Hidden`, IMHO. 
@paked @otraore ?
=> MouseSystem now skips hidden entities

math.go, math_test.go
A boolean is returned together with the intersecion point to indicate if there is intersection between the two given lines.
Fix for issue #339
=> LineIntersection now tells if lines intersect - #339

common/render_shaders.go, engo_glfw.go, engo_js.go, engo_mobile.go
There were a few things wrong with the code for scaling window size vs canvas size; the canvas (frame buffer) size was getting conflated with window size in `SetFramebufferSizeCallback`, and some of the code dealing with mouse coords was missing the scale factor. The last change was to adjust the scale of the projection matrix in the shaders to match the adjusted mouse coords. I wasn't sure if there was a better way to do this, but adjusting these few cases in `render_shaders.go` works. 
Fixes #379 
Fixes #388
=> Fix framebuffer scale issue for OSX retina

common/animation.go, common/audio.go, common/audio_unsupported.go, common/collision.go, common/interfaces.go, common/interfaces_test.go, common/mouse.go, common/render.go
Attempt 3:
Created a new file called interfaces.go, which defines interfaces to requiring Get__Component methods to allow AddByInterface methods to recieve an interface, instead of a list of components
Added AddByInterface methods to all common systems that have an Add method.  These receive an interface defined in interfaces.go, to make adding an entity to a system work with a single parameter.
Added Get__Component method to each component so that any containing interface automatically satisfies interfaces required by AddByInterface methods.
created a new file called interfaces_test.go, to make sure all new code is tested.  Could not add fail tests easily as the whole thing is typesafe, so would not compile.
=> Get__Component and AddByInterface

engo_glfw.go
On some systems a right click also triggers a CursorPos callback, and left click with rapid mouse movement also triggers a CursorPos Callback. Since Release and Press actions are usually prefered to be reported over the Move action, an if statement ensures that the mouse button clicks are reported over mouse movement. Edit: This was written in order to solve Issue#417
=> Fixed Mouse Action being overwritten

common/collision.go, common/collision_test.go
This method gets the center position of the space component instead of its top-left point.
The go idiomatic way would be to rename Center(p) to SetCenter(p) and GetCenter() to Center(). But since that change would break backwards-compability I went for GetCenter() as the new method name.
If you would like the methods to be renamed to SetCenter(p) and Center() I can change the commit accordingly. As a first time contributor I think it is not up to me to decide whether or not a change like this should break backwards-compability. :)
=> New method SpaceComponent.Center()

common/collision.go
flipped the signs on collision.go initial bounds for AABB(), so that AABB() returns the actual max bounds of the Space Component, rather than the max bounds of +/- MaxFloat32
fixes #441
=> flipped the signs on collision.go initial bounds for AABB()

engo_mobile.go
Needed to clean up Gl context when the game closes. Otherwise the game just freezes and crashes on next restart unless it's force closed.
We also want to use the device's lifecycle and cross-off when closing rather than use a break to get out of the main loop.
#447
=> close game for gomobile

common/font.go
This is for issue #454 but I also found a few pixels on the right of certain glyphs were not being displayed, such as the top right of capital V.
=> Font cutoff

common/font.go
draws the font atlas much more effeciently. Gets all the dimensions for the image before it creates the image, so the image size is exactly the right size. It also only ever has one image rendered, so it doesn't multiply memory used for multiple images. I also am using the draw function from image/font, so that when the truetype font library is put into image/font, it's ready to be used there instead of using the legacy draw methods from the old truetype library.
=> font atlas

common/mouse.go
Code is pretty simple. Added a new External bool to common.MouseComponent and one Internal bool. Mimiced the left mouse stuff for the right mouse stuff. 
Working great on my WIP game.
=> Fix Issue #463: add right mouse dragging to common/mouse.go

engo.go, engo_glfw.go
This adds a `NotResizable` option that hints to `GLFW` that the window
should not be resizable if specified true.  `GLFW` defaults resizable
to true, so `RunOpts` does as well.
With `NotResizable: true` specified:
=> Add "NotResizable" RunOpts option

common/interfaces.go
Added whitespace to make the Overview section in godoc for package common render much nicer. Faces, Ables, etc., now are nice headings in godoc. 
Also added punctuation to make the comments complete sentences. 
Also reflowed the comments.
=> common: godoc comments fix in common/intefaces.go

common/camera.go
I spent several minutes tweaking MinZoom thinking it would let me zoom out farther, and lo and behold, it's the opposite! Added some documentation so future people won't have the same issue and can realize that you actually increase MaxZoom in order to zoom "out".
=> add documentation to MinZoom and MaxZoom in common/camera.go

assets.go, engo.go, engo_mobile.go, engo_mobile_bind.go
Allows you to build an android (and possibly ios but don't have access to a Mac) library that uses Engo as part of a GlSurfaceView in Android. In currently working on a tutorial for it's use on github.com/Noofbiz/mousetests. I'll update on here when the full tutorial is done. Basically you can create a library that's a replica of the main function except instead use Start(int, int) instead of main. Then create an android glue library within the project that gets called from Java. Then you can build the library package using gomobile bind -tags=mobilebind
This will generate the  . aar file that you add to your Java code for Android. I'll try to get the full tutorial up sometime this evening, but you guys can check out the code now and let me know if you have any comments or suggestions.
=> Reverse android bindings

common/tmx_level.go
ran go fmt as well, which caused the import/comment shuffling.
=> common: parse gid from tmx objects

common/collision.go
The purpose of this pull request is to make collisions between equal objects act equally.
Currently, the object who comes earlier in the list is checked for collision first (for loop, hard to avoid)
This first object is then moved off of the second, and so the second doesn't even register the collision when his turn comes around.
An unfortunate consequence of this is that if both elements are free to move around, the second in the list will always push the first around, but the first cannot push the second.
This recently cuased a lot of confusion for a user on gitter.
To fix this, we ask if the second element also has a main collision with the first object, (only if the collision is solid). If so we move them both back half the escape distance, and dispatch a message for both of them.
=> Equal collision

engo.go, engo_glfw.go, engo_mobile.go, engo_mobile_bind.go
Just some cleanup, moving canvasWidth and canvasHeight to engo.go since it's used by every build tag, and now for headless mode too
=> Move canvas width/height to engo since all the builds use it

clock.go, clock_test.go
Added tests to test the Clock. It adds 3 seconds to the total test time, but because the FPS ticker is setup to go once every second, it seems like it's going to have to be this way. Anyone have any suggestions that might speed this up?
=> clock unit tests added

common/camera.go, common/camera_test.go, common/render.go
Now panics when more than one `CameraSystem` is added to a `World`. Added documentation to `CameraSystem` to reflect this, and to `RenderSystem` to warn that it adds a `CameraSystem` if one isn't present. The panic also says this to provide a hint for anyone with issues. Also added tests for the panic.
=> Warning if multiple cameras are added

common/render.go, common/render_shaders.go
This allows the RenderComponent's Repeat to work properly. It's based on the size of the SpaceComponent relative to the size of the RenderComponent's Drawable * Scale. This closes #237 
It adds a new TextureRepeat as the default, NoRepeat. If this is selected (or none are), it will draw the texture as if the View() were 0,0,1,1; just like it did before. 
However, if another one is chosen it will now look at the SpaceComponent's size to get how big it should draw the the screen, as well as the results for the View. If the SpaceComponent is smaller, it'll only draw a portion of the texture; if it's larger it'll repeat the texture based on the selected Repeat.
=> Renders the texture based on the space component's size and render component's repeat

common/render.go, common/render_shaders.go
They don't work with repeat though. Seems to be an issue with earlier versions of ogl
=> fixed sprite sheet back to working properly.

axis.go, axis_test.go, common/camera.go, common/camera_test.go, common/mouse.go, common/render_shaders.go, demos/edgescroller/escroller.go, demos/incrementalcamera/incrcamera.go, demos/keyboardscroller/kbscroller.go, demos/zoom/zoom.go, engo.go, engo_glfw.go, engo_js.go, engo_mobile.go, engo_mobile_bind.go, input_keys_glfw.go
Added a GlobalScale option that'll scale the entire game by that amount.
If the Scale is set, it'll adjust mouse clicks and rendering, but if the
user is utilizing mouse positioning or a custom render system, they'll
need to be aware of if this is set and what it sets to. Default is just
engo.Point{1,1}. Fixes #270
=> Add GlobalScale option

common/animation.go, common/audio.go, common/collision.go, common/interfaces.go, common/mouse.go, common/render.go
Added not flags to the systems so you can add the "Not" components to entities you want to flag as not part of a system when utilizing the auto-add ecs.World.SystemInterface() function. Also changed AddByInterface to take a ecs.Identifier instead of the specific -able to be more generic and work with the ecs implementation.
Fixes #387
=> added not flags and the add by interface to work with new ecs setup

common/render_shaders.go
fixes the missed pixels at rectangle border corners. Using DRAW_LINES instead and drawing each line individually. The error was caused by the border width not being accounted for, leaving blank spaces at each corner. Fixes #408
=> rectangle border fix

engo_glfw.go, engo_mobile.go, input_keys.go, input_keys_glfw.go
Closes #371, #306, and #370. Build tags now properly include building and binding iOS using gomobile. Updated ergo.io/gl to also use these build tags.
=> changed build tags to include ios

common/collision.go
Bug:
When a CollisionEntity with the Main field set is intersecting two or more other entities, (for example, when it's pushed into the ground by gravity where two ground tiles meet) it is affected by both Minimal Translations, when one would be sufficient.
Fix:
After applying the first MinimalTranslation the new position of the CollisionEntity is used as further reference to all other isIntersecting checks
=> fixed duplicate movement in CollisionSystem

common/font.go
font atlas total width now gotten after width added to prevent clipping edge glyphs
=> Prevent font atlas clipping

engo.go, engo_glfw.go, scene.go
Fixes issue #575 : when running a game and closing it via Terminal via `os.Interrupt` or `syscall.SIGTERM` (aka CTRL+C) 8 race conditions are detected if the game is built or run with the `-race` flag
=> Fixes race conditions 

message.go, message_test.go, scene.go
Added StopListen and ListenOnce to the MessageManager
Taking a first shot to resolve #584 
As this is my first Golang project, please check the code for beginner mistakes :)
What I'm currently not sure about: Locking
Dispatch() only holds a RLock when dispatching the individual handlers. However, StopListen() might (and ListenOnce certainly WILL) modify the handlers list while Dispatch() is iterating over it. Not entirely sure, but this seems very problematic. 
Potential solution: Have Dispatch() use Lock() instead of RLock(). Have StopListen() test the lock. If the lock is open, we can simply remove the handler without special care. If it's already locked (indicating that Dispatch() is currently running), add the MessageHandlerID to some "to be deleted" list. After processing handlers, …
=> #584 Improved message manager 

engo.go, engo_empty.go, engo_glfw.go, input_keys.go, input_keys_glfw.go
Goes with https://github.com/EngoEngine/gl/pull/15 to create a completely headless system that can run on servers without any gl or glfw dependencies
=> add headless engo for servers that does not use glfw or any window

assets.go
Resolved #324 by replacing the default `filepath.Ext()` function used to get extension from a given url to a custom function `GetExt()` which additionally also handles extensions with `.` in them.
=> Allow registration of extensions with dot in them

common/render.go
This will allow custom shaders to know if their shaders have errors and don't work
=> add panic if shaders don't compile

message.go
There was a race condition during message dispatching that could
potentially cause a panic (and thus a crash) if the list of message
handlers was modified while a message was actively being dispatched.
The solution here is to make a copy of the the handler list before
iterating over it.
=> Fix race condition in message dispatching.

engo_glfw.go
Since one ticker.C element can be buffered in case the ticker falls
behind a bit, there is a chance that when the glfw window is closed,
closeEvent() will be fired twice.
=> Fix a race condition when engo glfw is closed.

common/render.go
In renderEntityList.Less, the shader comparison was incorrect. Instead
of using the valuie of the render component's shader (a pointer) it
was instead comparing the address of the pointer variable of the render
component's shader (address of the pointer). This was resulting in the
comparison always being false, even if it was the same shader.
=> Fix issue with comparing shaders.

common/render.go, common/render_shaders.go, math.go
Hi,
after thinking about frustum culling for 2D, I've came up with this simple solution. I'm not 100% sure this is really faster so this needs to be tested.
If this could be optimized, it could be a performance gain. 
the cpu-profiler tells me that it spend 68% of all the `RenderSystem` time in `ShouldDraw` and 86% of that time is spend in `engo.MultiplyMatrixVector`
=> view-culling for basic shader

math.go
due to a lot of calls in `ShouldDraw` all those allocations of the float slices trigger the GC more often then needed. 
this change reduces the allocation from 3 slices per call to 0.
=> prevent allocations on MultiplyMatrixVector

common/animation.go
due to parenting being added to basic entity in ecstatics
=> animation map has to be uint64 since basicentity can't be used anymore

common/audio.go, common/audio_test.go
when switching scenes with the audio system the channel wasn't closing, and trying to create a new player caused context panics in oto.
=> fix channel closing and oto Context errors

common/render.go, common/render_js.go, common/render_notjs.go
I'm not sure why, but the current version of Engo has a `zIndex` as private value. 
The only way to set ZIndex is by using `SetZIndex`, at the current version. That makes it impossible to set the value in advanced (at the `&RenderComponent{}`). In my case doesn't make any sense to set the ZIndex using the `SetZIndex`, since some elements have always the same ZIndex (like: background is 0 and player is 1).
I'm not aware of any issue of that change, but I don't know what wasn't public before.
=> Change z-index to public

common/mouse.go
Previously, when the mouse action was neutral, the `Dragged` state of the mouse was reset to `false`. This change fixes it by keeping it set to `true` as long as one of the mouse buttons is down, requiring a mouse release before the `Dragged` state is exited.
=> Keep mouse drag when mouse action is neutral

common/mouse.go
Missed a case when fixing the `Dragged` flag for the mouse. In this case, the mouse was Clicked but unmoved, which would register both as a click and a drag. With this fix, if the mouse is pressed down and stays in the same place, it is considered to be `Clicked`. If it moves at some point while still pressed, the mouse will be `Dragged ` as long as there is no mouse release.
=> Fixed missed case in setting Dragged flag

common/render_filetype.go, common/texture_atlas.go
- Add TextureAtlas loader to the File Loader based on xml exports from [TexturePacker](https://www.codeandweb.com/texturepacker)
- Make it the default loader for xml files
- Use a singular `ImageLoader` object for `engo.Files` to save memory allocations
- Add Viewport to `TextureResource` and use it if defined in `LoadedSprite(..)`
- Allows the use of the singular sprite sheet texture because singular sprites will be retrieved from the viewport of it
I tried to make it so that users can continue using `common.LoadedSprite` regardless of if they're using a `TextureAtlas` or not. This means that the texture is added to the image loader manually and is referenced using the file url for it.
For example: 
`<SubTexture name="enemyGreen1.png" x="425" y="552" width="93" height="84"/>`
That sprite …
=> Add support for Texture Atlases (spritesheets)

.github/workflows/qa.yml, engo_js.go
syscall/js no longer supports using straight == to compre js values.
=> no longer js.Value compare using ==

engo_glfw.go, engo_js.go, engo_sdl.go, input.go, input_keys.go
Something to note is that SDL supports modifiers being identifiable by their position on the keyboard. So left shift vs right shift. GLFW as far as I know, does not. To keep the API simple and not requiring the end users to use bitwise operations to check their Modifiers, I just did the checks within the game loop so the API is the same for both platforms. Going to be adding js support in an upcoming commit as well.
ex:
```go
if engo.Input.Modifier == engo.Shift {
log.Println("is shift")
}
```
=> Input key modifiers

engo_empty.go
I removed the fallthrough statement. Otherwise it already looked like the glfw version, so I think this should be the necessary changes to fix the compile error I received in #738 
There is still another problem with the headless build: The oto dependency is causing trouble, if no drivers are installed on a build system. But I'm not sure if this should be fixed in this pull request (or even in this repository)
=> Removed fallthrough case since it caused build errors

common/level.go, common/tmx_level.go
This adds support for tile animations created in editors like Tiled and saved into the TMX files.
Currently, I have not found a good way to use the animation rate set in the editor, so that must be set when using the tile later and creating an AnimationComponent.
Here is an example of how to then implement the animation:
```go
tiles := []*Tile{}
for idx, layer := range level.TileLayers {
for _, tile := range layer.Tiles {
if tile.Image == nil {
log.Printf("Tile has no image at point: %v", tile.Point)
}
t := &Tile{BasicEntity: ecs.NewBasic()}
if len(tile.Drawables) > 0 {
t.AnimationComponent = common.NewAnimationComponent(tile.Drawables, 0.1)
t.AnimationComponent.AddDefaultAnimation(tile.Animation)
}
t.RenderComponent = common.RenderComponent{
Drawable:    tile.Image,
Scale: …
```
=> Added support for tile animations from TMX files

common/render_shaders_shapes.go, demos/shapes/shapes.go
I was counting the vertex that sets it to the center as a vertex that draws the circle, which led to an off-by-one offset in the circle. This caused the angles to be a little smaller than they should've been when using `Circle.Arc`, as well as double drawing of some triangles when the transparency was set to something other than 1 or 0.
Fixes for #766
=> Double drawing and proper number of verts

assets.go, common/tmx_filetype.go, common/tmx_level.go
Hello,
this little patch fixes an issue when trying to load tmx files that reference tsx files
it tries to be as unobtrusive as possible by defining a new interface and only using it if the given file loader supports this new interface.
Cheers,
Florent
=> tmx: fix the tmx/tsx loading

common/render_shaders_default.go
Default shader will now translate a sprite when a negative scale is used so it draws in line with where the SpaceComponent is.
=> Negative Scale Drawing

common/level.go, common/tmx_level.go, common/tmx_level_test.go, demos/adventure/adventure.go, demos/adventure/assets/example.tmx
When working on my project I noticed that Engo is losing the information about flipped tiles in the tile map when converting from the TMX structure to the internal model. This pull request adds this feature by the means of adding a Rotation in degree to the internal TMX Tile model. I just now went this path, if this is in some way not how you intend to solve this problem, please let me know 🚀  I hope this is also in your interest and thank you for this really fun 2D engine!
This adds also a changed map to the `adventure` demo with 4 rotated flowers on the ground.
fixes #779
=> Add rotation based on TMX flipping flag

common/font.go, common/spritesheet.go
To access preloaded sritesheets and fonts without having to pass pointers around scenes/systems.
=> added loadedspritesheet and loadedfont functions
